### PR TITLE
feat(plugins): Use extensionDependencies field of package.json to get dependencies

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Parse extensionDependencies field of vsix to detect plugin dependencies
rename extensions field in `che-theia-plugins.yaml` to  `extension` as only one vsix is defined per vsix anyway.

meta.yaml will contain all vsix of dependencies and che-theia-plugin.yaml will contain the dependencies to other plug-ins

also make sure all generated yaml are not multiline

It'll simplify devWorkspace plugins dependencies as we'll have graph of dependencies and avoid duplicates

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15376

### How to test this PR?
Check meta.yaml, they should contain the same data than before

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: I740d3dcfbe59d777594e628fdb4498c7581a3997
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by ericwill — COMMENTED** [review]
Checked the `meta.yaml` output and it seems fine to me. :+1:  Please don't forget to document the new `che-theia-plugins.yaml` fields in the CONTRIBUTE.md file, as this can get out of date easily.

**Comment by tsmaeder** [comment]
@benoitf so this will add a copy of the dependency *.vsix to every che-plugin that declares that dependency. So may end up with multiple copies of the same *.vsix in the same che workspace. I don't think that is a use case we support 100%.
Shouldn't we strive to translate dependencies on *.vsix files into dependencies on the che plugins that contain that *.vsix file? That's why we have the remote API invocations, no?

**Comment by benoitf** [comment]
> @benoitf if I understand correctly, this will add a copy of the dependency *.vsix to every che-plugin that declares that dependency. So may end up with multiple copies of the same *.vsix in the same che workspace. I don't think that is a use case we support 100%.

well this is what is done in current meta.yaml (so here we don't change anything). If you compare current meta.yaml and what is generated by the PR, the content is identical.

if you deploy both `openshift-connector` and `vscode-yaml` it already ends up with multiple vscode yaml extensions

https://che-plugin-registry-main.surge.sh/v3/plugins/redhat/vscode-openshift-connector/latest/meta.yaml
https://che-plugin-registry-main.surge.sh/v3/plugins/redhat/vscode-yaml/latest/meta.yaml

> Shouldn't we strive to translate dependencies on *.vsix files into dependencies on the che plugins that contain that *.vsix file? That's why we have the remote API invocations, no?

This is what this PR does for dev workspaces (not the generated `meta.yaml` files consumed by plug-in broker but the `che-theia-plugin.yaml` fragment) we have now dependencies explicitly defined so if someone want to install both `openshift-connector` and `vscode-yaml` as there is dependency explicitly defined it will end up only with one extension being installed. (client can see this dependency and behave accordingly)

**Comment by tsmaeder** [comment]
> 
> well this is what is done in current meta.yaml (so here we don't change anything). If you compare current meta.yaml and what is generated by the PR, the content is identical.
> 

As I understand it, that was a stop-gap solution to make it work until we can fix the underlying problem: this PR seems to automate the stop-gap, not fix the underlying problem.

> This is what this PR does for dev workspaces (not the generated `meta.yaml` files consumed by plug-in broker but the `che-theia-plugin.yaml` fragment) we have now dependencies explicitly defined so if someone want to install both `openshift-connector` and `vscode-yaml` as there is dependency explicitly defined it will end up only with one extension being installed. (client can see this dependency and behave accordingly)

Could you be more specific here? I don't see how that works.

**Comment by benoitf** [comment]
> As I understand it, that was a stop-gap solution to make it work until we can fix the underlying problem: this PR seems to automate the stop-gap, not fix the underlying problem.

it does not fix the problem for che-server workspaces (meta.yaml) as we don't want to introduce enhancements on plugin broker implementation but for DevWorkspaces (che-theia-plugin.yaml)


> Could you be more specific here? I don't see how that works

if you check
https://pr-check-941-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-openshift-connector/latest/che-theia-plugin.yaml

you'll see 
```
dependencies:
  - che-theia/che-openshift-authentication-plugin
  - ms-kubernetes-tools/vscode-kubernetes-tools
  - redhat/vscode-yaml
 ```
and only one vsix file to install

instead of having all vsix of dependencies being listed there

**Comment by tsmaeder** [comment]
But if you add a second che plugin with a *.vsix that also has vscode-yaml as a dependency, you'll still end up with vscode-yaml running in more than one sidecar, correct?

**Comment by benoitf** [comment]
> But if you add a second che plugin with a *.vsix that also has vscode-yaml as a dependency, you'll still end up with vscode-yaml running in more than one sidecar, correct?

if you have two plugins like `redhat.vscode-openshift-connector` [1] and `ms-kubernetes-tools.vscode-kubernetes-tools` [2]

they both have

```
dependencies:
  - redhat/vscode-yaml
```

so when we'll start a devWorkspace we know that we'll need to add `redhat.vscode-openshift-connector`, `ms-kubernetes-tools.vscode-kubernetes-tools` and `redhat/vscode-yaml` plug-ins but there will have only one `redhat/vscode-yaml` vsix file in its own sidecar.

I don't see why we would `end up with vscode-yaml running in more than one sidecar`


[1]
https://pr-check-941-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-openshift-connector/latest/che-theia-plugin.yaml

[2]
https://pr-check-941-alpine-che-plugin-registry.surge.sh/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/latest/che-theia-plugin.yaml

**Comment by tsmaeder** [comment]
But if redhat.vscode-openshift-connector and ms-kubernetes-tools.vscode-kubernetes-tools each run in their own sidecar, how do you know which one you need to add redhat/vscode-yaml  to? In which sidecar are we running vscode-yaml? The theia container?

**Comment by benoitf** [comment]
> But if redhat.vscode-openshift-connector and ms-kubernetes-tools.vscode-kubernetes-tools each run in their own sidecar, how do you know which one you need to add redhat/vscode-yaml to? In which sidecar are we running vscode-yaml? The theia container?

in the one that the yaml plug-in defines there
https://pr-check-941-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-yaml/latest/che-theia-plugin.yaml

```yaml
sidecar:
  name: vscode-yaml
  memoryLimit: 256Mi
  cpuLimit: 500m
  cpuRequest: 30m
  image: 'quay.io/eclipse/che-plugin-sidecar:node-c939ba4'
```

**Comment by tsmaeder** [comment]
OK, so it's doing exactly what I was asking for in devworkspace and we're not fixing the behaviour in the che-server/plugin broker world, correct?

**Comment by benoitf** [comment]
@tsmaeder correct

**Review by ericwill — APPROVED** [review]

**Pull request merged**
