### PR TITLE
Enable subpath mode for Che Theia editor in devworkspaces

### PR DESCRIPTION
**Pull request by xbaran4**
### What does this PR do?
adds urlRewriteSupported attribute for che theia endpoints so that they can be served on subpath instead of subdomain
also adds this attribute to che-machine-exec endpoint which is not mentioned in the referenced issue below

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20180

### How to test this PR?

1. create patch.yaml: 
```shell
echo \
"spec:
  server:
    pluginRegistryImage: quay.io/pbaran/che-plugin-registry:singlehost-theia
    pluginRegistryPullPolicy: Always" \
> patch.yaml
```
2. deploy che:
```shell
  chectl server:deploy --platform=openshift --workspace-engine=dev-workspace --che-operator-cr-patch-yaml=patch.yaml 
```
3. create workspace from quarkus sample
4. run:
```shell
kubectl get devworkspace --namespace=${USERNAMESPACE}
```
verify that devworkspace info shows theia serving on subpath

5. run:
```shell
kubectl describe configmaps --namespace=eclipse-che
```
verify that workspace configmap contains endpoints with subpath url

6. run:
```shell
kubectl get route --namespace=${USERNAMESPACE}
```
verify that there arent routes for che theia

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
works for me with plugin registry image you've built.

one small correction in "How to test this PR?", in step 5, the configmap should be in Che namespace, not user one.

**Review by sparkoo — APPROVED** [review]
tested on local crc, works as expected

**Review by svor — APPROVED** [review]
LGTM
@benoitf @nickboldt do we need these changes in downstream as well?

**Comment by svor** [comment]
@xbaran4 could you please merge with master to pick up last changes related to tests: **test(pr-check): Disable the 'TypescriptPlugin' test in the PR-check suite** #1017. It is needed to make openshift/test-pr-check happy.

**Comment by svor** [comment]
@xbaran4 v7-plugins-test-pr-check fails because it cannot open a workspace created by factory.

Could you please check if it doesn't related to your changes:
- create a workspace by using factory
- open the workspace by opening factory url

**Comment by Ohrimenko1988** [comment]
> @xbaran4 v7-plugins-test-pr-check fails because it cannot open a workspace created by factory.
> 
> Could you please check if it doesn't related to your changes:
> 
> * create a workspace by using factory
> * open the workspace by opening factory url

Please pay attention that test scenario is:
 - Initiate workspace creation using factory url
 - After the workspace start workspace should be automatically opened

As far as PR-check continuously fails because of workspace doesn't open after start I suppose that may be related to the PR changes.

**Comment by xbaran4** [comment]
I took devfile from the quarkus rest api sample and tested the scenario manually: 
https://www.youtube.com/watch?v=hO93cCW6jVE&ab_channel=PavolBaran
Where else could the problem be?

**Comment by svor** [comment]
> I took devfile from the quarkus rest api sample and tested the scenario manually:
> https://www.youtube.com/watch?v=hO93cCW6jVE&ab_channel=PavolBaran
> Where else could the problem be?

@xbaran4 Thank you for checking that! I cannot understand why but tests were unstable yesterday.

**Comment by benoitf** [comment]
@svor @xbaran4 yes we need to backport these changes in CRW

**Comment by svor** [comment]
@xbaran4 could you please create a similar PR in [CRW](https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/che-editors.yaml)

**Pull request merged**
