### PR TITLE
fix(python-plugin): Fix errors when loading python plugin. Installing pylint and tools in the dedicated venv

### PR DESCRIPTION
**Pull request by sunix**
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>

### What does this PR do?
Fix problems with python plugin 

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
Fix https://github.com/eclipse/che/issues/20093

### How to test this PR?
Try the new plugin with the default python devfile. Make sure there is no error popping up when opening a .py file and autocomplete is working and that.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
as a side note, it looks odd to rely on `;` and not `&&` in RUN instructions as we may have failures not failing the build

**Comment by sunix** [comment]
> as a side note, it looks odd to rely on `;` and not `&&` in RUN instructions as we may have failures not failing the build

OK let me give a try with `&&`

**Review by svor — APPROVED** [review]
Tested on che-dogfooding instance and i have not seen error that python is not installed. Also autocomplete is working
python

**Comment by sunix** [comment]
please do not merge:
For some reasons when I install the jupyter in the venv, it is failing to build in some architecture.
I am trying to find a workaround and now it's building but it is not working in all cases.

**Pull request merged**
