### PR TITLE
Icon path must be relative to plugin registry root folder

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Removes `/v3...` at the beginning of the icon path.
Having `/v3` gives wrong icon path for single root Che deployment.

It must work for both
- `https://plugin-registry-eclipse-che.apps-crc.testing/v3`
and
- `https://che-eclipse-che.apps-crc.testing/plugin-registry/v3`

If the icon without `/v3`, to show the icon Theia will just concatenate plugin registry root and icon path.

It needs to merge this PR together with https://github.com/eclipse-che/che-theia/pull/1118.

### Screenshot/screencast of this PR

Screenshot from 2021-05-28 00-17-38

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19771

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by svor — APPROVED** [review]
LGTM. Tested on single-host
screenshot-172 17 0 2 nip io-2021 05 31-19_01_10

**Comment by ericwill** [comment]
@vitaliy-guliy please check to make sure it works with the devfiles we publish to GitHub pages, i.e.: https://eclipse-che.github.io/che-devfile-registry/7.31.0/devfiles/nodejs-yarn/devfile.yaml as an example. Note how these devfiles have `registryUrl` for the plugin definitions.

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy please check to make sure it works with the devfiles we publish to GitHub pages, i.e.: https://eclipse-che.github.io/che-devfile-registry/7.31.0/devfiles/nodejs-yarn/devfile.yaml as an example. Note how these devfiles have `registryUrl` for the plugin definitions.

I've created an issue for this case https://github.com/eclipse/che/issues/19898

Displaying of icons for plugins with `registryUrl` was not implemented. Theia will always try to load the icon from default registry.

**Comment by ericwill** [comment]
> > @vitaliy-guliy please check to make sure it works with the devfiles we publish to GitHub pages, i.e.: https://eclipse-che.github.io/che-devfile-registry/7.31.0/devfiles/nodejs-yarn/devfile.yaml as an example. Note how these devfiles have `registryUrl` for the plugin definitions.
> 
> I've created an issue for this case [eclipse/che#19898](https://github.com/eclipse/che/issues/19898)
> 
> Displaying of icons for plugins with `registryUrl` was not implemented. Theia will always try to load the icon from default registry.

Thank you!

**Pull request merged**
