### PR TITLE
chore: increase memoryLimit for che-code-injector component

### PR DESCRIPTION
**Pull request by aelbarkani**
### What does this PR do?

Increase RAM for che-code-injector component.

### What issues does this PR fix or reference?

Fixes https://github.com/eclipse-che/che/issues/21719.
OOMKill in che-code-injector initContainer (it seems this fix is not enough anymore: https://github.com/eclipse-che/che-plugin-registry/pull/1558).

### How to test this PR?

Deploy a workspace in Eclipse Che with checode editor.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by svor** [comment]
Hello @aelbarkani 
Recently editors definitions were moved to che-operator side and che-plugin-registry is going to be deprecated in the future, could you please make your changes in https://github.com/eclipse-che/che-operator/tree/main/editors-definitions for both che-code editors (latest and insiders)

About OOMKill error. I didn't see this error when deploying che, could you please describe how you reproduce this problem.

**Comment by aelbarkani** [comment]
@svor this is the devfile I'm using:

```

schemaVersion: 2.3.0
metadata:
  name: univesal-workspace-nix

components:
  - name: nix
    attributes:
      controller.devfile.io/merge-contribution: true
    container:
      image: nixos/nix:2.24.5@sha256:4ad79a0ab633944869a37921f096d35a3f2c7a0275d98b7bfa0cd3cba5a6b96e
      memoryLimit: 8Gi
      cpuLimit: '4'
      command: ["/bin/sh", "-c", "cp /configs/vscode/settings.json /checode/remote/data/Machine && tail -f /dev/null"]

      env:
        - name: HOME
          value: /home/nix
        - name: VSCODE_NODEJS_RUNTIME_DIR
          value: /home/nix/.nix-profile/bin
        - name: PATH
          value: /root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/home/nix/.nix-profile/bin
      volumeMounts:
        - name: nix-volume
          path: /nix/
        - name: home
          path: /home/

  - name: nix-copy
    container:
      image: nixos/nix:2.24.5@sha256:4ad79a0ab633944869a37921f096d35a3f2c7a0275d98b7bfa0cd3cba5a6b96e
      memoryLimit: 4Gi
      cpuLimit: '1'
      command: ["/bin/sh", "-c"]
      args: 
        - |
          if [ ! -f /nix-tmp/copy-finished ]; then
            rm -rf /nix-tmp/*
            cp -nav /nix/* /nix-tmp/
            touch /nix-tmp/copy-finished
          else
            echo "Nix volume already copied."
          fi
      volumeMounts:
        - name: nix-volume
          path: /nix-tmp/

  - name: nix-config
    container:
      image: nixos/nix:2.24.5@sha256:4ad79a0ab633944869a37921f096d35a3f2c7a0275d98b7bfa0cd3cba5a6b96e
      memoryLimit: 4Gi
      cpuLimit: '1'
      command: ["/bin/sh", "-c"]
      args:
        - |
            set +x

            mkdir -p /home/nix/.config/home-manager
            mkdir -p /home/nix/.config/nix


            if [ -f /configs/nix/nix.conf ]; then
            cp /configs/nix/nix.conf /home/nix/.config/nix/nix.conf
            else
              echo "Warning: /configs/nix/nix.conf not found, skipping copy."
            fi

            if [ -f /configs/nix/home.nix ]; then
              cp /configs/nix/home.nix /home/nix/.config/home-manager/home.nix
            else
              echo "Warning: /configs/nix/home.nix not found, skipping copy."
            fi

            if [ -f /configs/nix/flake.nix ]; then
              cp /configs/nix/flake.nix /home/nix/.config/home-manager/flake.nix
            else
              echo "Warning: /configs/nix/flake.nix not found, skipping copy."
            fi

            # VSCode configuration
            if [ -f "/configs/vscode/settings.json" ]; then
                cp /configs/vscode/settings.json /checode/remote/data/Machine/settings.json
            else
                echo "Warning: VSCode settings file or destination directory not found."
            fi

            # VSCode Continue.dev configuration
            if [ -f "/configs/vscode/extensions/continue/config.json" ]; then
                mkdir -p $HOME/.continue
                cp /configs/vscode/extensions/continue/config.json $HOME/.continue
            else
                echo "Warning: Continue.dev config file not found."
            fi
            

            # NodeJS necessary for Eclipse Che VSCode
            nix profile install nixpkgs#nodejs_22

            # Install Nix Home manager
            nix run home-manager/8a1671642826633586d12ac3158e463c7a50a112 -- init --switch

            # Fix permissions for zsh
            nix path-info github:NixOS/nixpkgs/ed0fe13cc637546cad8c3ee903a23459b59f5080#zsh | xargs chmod -R 755
            nix path-info github:NixOS/nixpkgs/ed0fe13cc637546cad8c3ee903a23459b59f5080#oh-my-zsh | xargs chmod -R 755
      env:
        - name: HOME
          value: /home/nix
        - name: PATH
          value: /root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/home/nix/.nix-profile/bin    
      volumeMounts:
        - name: nix-volume
          path: /nix/
        - name: checode
          path: /checode/
        - name: home
          path: /home/

  - name: nix-volume
    volume:
      size: 20Gi

  - name: home
    volume:
      size: 20Gi

commands:
  - id: nix-copy
    apply:
      component: nix-copy

  - id: nix-config
    apply:
      component: nix-config

events:
  preStart:
    - nix-copy
    - nix-config

```
Creating a workspace through Eclipse Che dashboard:
eclipse-che apps sip-1 internal blakane com_dashboard_

And here is the result:
console-openshift-console apps sip-1 internal blakane com_k8s_ns_che-kube-admin-che-fffy6t_pods_workspacef0ec8bcefa0d4695-8dcc85c6d-g8fzg (1)
console-openshift-console apps sip-1 internal blakane com_k8s_ns_che-kube-admin-che-fffy6t_pods_workspacef0ec8bcefa0d4695-8dcc85c6d-g8fzg

**Comment by aelbarkani** [comment]
@svor so should I close this PR ?

**Comment by svor** [comment]
@aelbarkani yes, this PR should be closed.

About the problem, I've tried to start a workspace using your devfile and got an error: `Error creating DevWorkspace deployment: Init Container nix-config has state CrashLoopBackOff`

from the nix-config component logs:
```
Warning: /configs/nix/nix.conf not found, skipping copy.
Warning: /configs/nix/home.nix not found, skipping copy.
Warning: /configs/nix/flake.nix not found, skipping copy.
Warning: VSCode settings file or destination directory not found.
Warning: Continue.dev config file not found.
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it
chmod: missing operand after '755'
Try 'chmod --help' for more information.
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it
chmod: missing operand after '755'
Try 'chmod --help' for more information.
```

**Pull request closed without merging**
