### PR TITLE
Added multiarch support by docker buildx

### PR DESCRIPTION
**Pull request by bivasda1**
Signed-off-by: Bivas Das <bivasda1@in.ibm.com>

### What does this PR do?
Enables docker buildx support in GitHub Actions job to build and publish multiarch docker images. All the workflows (nightly build, PR check, and release) are updated to have multiarch support.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by bivasda1** [comment]
@ericwill Could you please review this PR.

- Added multi-arch support  for these `.github/workflows/build-jobs.yml` and `.github/workflows/release.yml`
- Separately Added Platformfile

**Comment by ericwill** [comment]
One thing we need to think about it has we will handle sidecar images (all Dockerfiles under the `sidecar/` folder). A lot of them are not multi-arch, so we will need to remove those plugins from the arches which do not support them. For example, the aarch64 registry shouldn't have plugins in it running on sidecars that don't support aarch64, etc.

**Comment by bivasda1** [comment]
> One thing we need to think about it has we will handle sidecar images (all Dockerfiles under the `sidecar/` folder). A lot of them are not multi-arch, so we will need to remove those plugins from the arches which do not support them. For example, the aarch64 registry shouldn't have plugins in it running on sidecars that don't support aarch64, etc.

My understanding, we have already Added Platform file with respect to sidecar images based on their availability to arch and enabled buildx, so we required to remove those plugins from the arches which do not support them?

**Comment by ericwill** [comment]
> > One thing we need to think about it has we will handle sidecar images (all Dockerfiles under the `sidecar/` folder). A lot of them are not multi-arch, so we will need to remove those plugins from the arches which do not support them. For example, the aarch64 registry shouldn't have plugins in it running on sidecars that don't support aarch64, etc.
> 
> My understanding, we have already Added Platform file with respect to sidecar images based(`sidecar/folder`) on their availability to arch and enabled buildx, so we required to remove those plugins from the arches which do not support them?

Yes, for example someone launching the plugin registry on aarch64 should not be able to install plugins that have no aarch64 sidecar. We should develop some exclusion method.

**Comment by bivasda1** [comment]
except `linux/amd64,linux/ppc64le,linux/arm64` it should exclude other Arches`[e.g aarch64]` and show a proper msg right?

**Comment by benoitf** [comment]
outdated

**Pull request closed without merging**
