### PR TITLE
chore: Update from ubi8/httpd-24:1-160 to ubi8/httpd-24:1-161

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
it looks like the Dockerfile for the ci job is not working

**Comment by svor** [comment]
replaced by https://github.com/eclipse-che/che-plugin-registry/pull/1103

**Pull request closed without merging**
