### PR TITLE
Update vscode-java to 0.82

### PR DESCRIPTION
**Pull request by tsmaeder**
Signed-off-by: Thomas Mäder <tmader@redhat.com>

### What does this PR do?
Updates vscode-java to the latest version (0.8.2) 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/20134

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by svor — COMMENTED** [review]
`revision: v0.75.0` should be updated as well

**Comment by benoitf** [comment]
since that PR has been created, VS Code java is at revision `1.1.0`

**Comment by svor** [comment]
> since that PR has been created, VS Code java is at revision `1.1.0`

@benoitf this PR was created a long time ago and the idea was to finish that work and apply vscode-java v0.82 which should work without some unexpected issues.

**Comment by svor** [comment]
We can apply current changes and update to the latest version in the future

**Review by svor — CHANGES_REQUESTED** [review]
I see some problems with the plugin initialization:
screenshot-che-eclipse-che 192 168 49 2 nip io-2021 12 15-20_42_49

```
ERROR:Activating extension 'Language Support for Java(TM) by Red Hat' failed:TypeError: Class extends value undefined is not a constructor or null
ERROR:Activating extension 'Java Test Runner' failed:Error: Dependent extension 'Language Support for Java(TM) by Red Hat' failed to activate.
```

**Comment by tsmaeder** [comment]
@svor yes, I put a comment in the issue.

**Review by svor — APPROVED** [review]
Tested on https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/ with che-theia:next and I  didn't detect any problem:

Screenshot from 2021-12-17 16-13-20

**Pull request merged**
