### PR TITLE
chore: remove --idle-timeout for che-theia editor since timeout is read from environment variable

### PR DESCRIPTION
**Pull request by dkwon17**
Signed-off-by: David Kwon <dakwon@redhat.com>

### What does this PR do?
Removes the `--idle-timeout` from `che-theia:next` and `che-theia:latest` editors.

The idle timeout is now being [read as an environment variable](https://github.com/eclipse-che/che-machine-exec/pull/208) set by [Che + DWO](https://github.com/eclipse-che/che-operator/pull/1443).

### What issues does this PR fix or reference?

Removing `--idle-timeout` from editors: https://github.com/eclipse/che/issues/21390

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by svor — APPROVED** [review]

**Comment by svor** [comment]
@dkwon17 can we merge this PR for 7.51.0 version ?

**Comment by dkwon17** [comment]
@svor yes, that would make sense since the che-machine-exec and che-operator changes are also in 7.51.x. Should I make a new PR for the[ 7.51.x branch](https://github.com/eclipse-che/che-plugin-registry/tree/7.51.x)?

**Comment by svor** [comment]
> @svor yes, that would make sense since the che-machine-exec and che-operator changes are also in 7.51.x. Should I make a new PR for the[ 7.51.x branch](https://github.com/eclipse-che/che-plugin-registry/tree/7.51.x)?

7.51.0 was released a few hours ago, need to ask @mkuznyetsov if we can do another release for plugin registry with these changes

**Pull request merged**
