### PR TITLE
Upgrade to VS Code Camel K 0.0.26 #19818

### PR DESCRIPTION
**Pull request by apupier**
### What does this PR do?

Upgrade to the newer version of VS Code Camel K 0.0.26. it provides kamel cli 1.5.0 by default.

### What issues does this PR fix or reference?

#19818

### How to test this PR?

https://issues.redhat.com/browse/CRW-609?focusedCommentId=13990929&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13990929
https://developers.redhat.com/blog/2020/01/24/apache-camel-k-development-inside-eclipse-che-iteration-1

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by apupier** [comment]
errors doesn't seem to be related to the PR (but I do not understand it very well):

```
==================== FINISH REPORT ========================
    JavaPlugin-------PASSED
    TypescriptPlugin-------FAILED
[ERROR] The plugin tests failed.
===========================================================
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-07-21T14:07:19Z"}
error: failed to execute wrapped command: exit status 1 
INFO[2021-07-21T14:07:29Z] Step plugins-test-pr-check-plugins-pr-check failed after 20m40s. 
INFO[2021-07-21T14:07:29Z] Running step plugins-test-pr-check-gather-aws-console. 
INFO[2021-07-21T14:07:49Z] Step plugins-test-pr-check-gather-aws-console succeeded after 20s. 
INFO[2021-07-21T14:07:49Z] Running step plugins-test-pr-check-gather-must-gather. 
INFO[2021-07-21T14:10:19Z] Step plugins-test-pr-check-gather-must-gather succeeded after 2m30s. 
skipped 48 lines unfold_more
[ERROR] The plugin tests failed.
===========================================================
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-07-21T14:07:19Z"}
error: failed to execute wrapped command: exit status 1
```

**Comment by apupier** [comment]
based on history, it is always failing https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-eclipse-che-che-plugin-registry-main-v7-plugins-test-pr-check with a similar error

**Comment by svor** [comment]
@apupier openshift-ci errors are not related to your changes, we have an issue for that

**Review by svor — COMMENTED** [review]
@apupier I see some errors related to Camlek extension but looks like it was started:
 
Screenshot from 2021-07-21 19-08-34

**Comment by apupier** [comment]
The completion is provided by the VS Code language Support for Apache Camel, not the VS Code tooling for Apache Camel K.
For scenarii to test:
- https://issues.redhat.com/browse/CRW-609?focusedCommentId=13990929&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13990929
- https://developers.redhat.com/blog/2020/01/24/apache-camel-k-development-inside-eclipse-che-iteration-1

We can see 2 error messages in output log:
* about mvn missing. This can be ignored. Mvn is not provided as vscode-java is nto working with vscode-camelk inside Che and so not provided. Mvn is required only when vscode-camelk is using features of vscode-java.
* about missing "Integration" resource type. This is because Che doesn't support to have a Camel K instance provided by default. Consequently, it is up to the user to configure a Camel K instance and configure the che workspace to connect to it.

We can see 2 messages as popup:
* kubectl version outdated. This is because the sidecar for kubernetes extension has nto ben updated for a while ENV MINIKUBE_VERSION=v1.18.1
* Activating xml extension failed. This is a bug for VS Code XML or Che. There is a [real dependency on vscode-commons extension](https://github.com/redhat-developer/vscode-xml/blob/d7801527025920557429b8d08b4c8f5ba06b9457/package.json#L59) but there is a [skipDependencies](https://github.com/eclipse-che/che-plugin-registry/blob/6907b68fc37fb2ef1fe79d50c9819a9588c0afef/che-theia-plugins.yaml#L469-L485) defined in registry. Uopgrading to xml 0.17.0 should fix that as the [dependency has been removed to vscode-commons](https://github.com/redhat-developer/vscode-xml/commit/b62f9e001c7422e35858aa291bc9b6cb5b4f32da#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) and the vs code api required is [1.37.0](https://github.com/redhat-developer/vscode-xml/blob/6cdc0b326bd6b245640c57659dc33249b4d800c7/package.json#L38)

**Review by svor — APPROVED** [review]
LGTM
screenshot-che-eclipse-che 192 168 49 2 nip io-2021 07 22-14_29_06

**Pull request merged**
