### PR TITLE
fix(push-ghpages): serving meta.yaml content when the full path is omitted

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
for the plugin registries published in gh-pages, serving meta.yaml content when the full path is omitted.
For instance https://eclipse-che.github.io/che-plugin-registry/7.30.1/v3/plugins/eclipse/che-theia/latest should display the content of the https://eclipse-che.github.io/che-plugin-registry/7.30.1/v3/plugins/eclipse/che-theia/latest/meta.yaml

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?

Fix https://github.com/eclipse/che/issues/19820

### How to test this PR?
Either trust me and try https://sunix.github.io/che-plugin-registry/nightly/v3/plugins/

or
1. start the devfile out of this branch,
2. build the registry with the predifine command
3. in a terminal of the builder:

        export GITHUB_ACTOR=yourgithubusername; 
        export GITHUB_TOKEN=yourgithubtoken;
        ./build/dev/publish-plugin-registry-to-gh-pages.sh

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ericwill — COMMENTED** [review]
shellcheck needs fixing

I assume we're always fetching the raw data? For example when I open https://sunix.github.io/che-plugin-registry/nightly/v3/plugins/redhat/java/latest/ in Firefox, I get the error: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by sunix** [comment]
> shellcheck needs fixing

I'll fix the shellcheck problems tomorow (my che cluster is down for the night)

> I assume we're always fetching the raw data? For example when I open https://sunix.github.io/che-plugin-registry/nightly/v3/plugins/redhat/java/latest/ in Firefox, I get the error: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

About the raw data, yes the surge.sh script is using index.html and it works, but the rendering is not nice in chrome. so i tried json. I'll see if i can try another file extension: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L44-L52 like index.cgi

**Comment by ericwill** [comment]
> > I assume we're always fetching the raw data? For example when I open https://sunix.github.io/che-plugin-registry/nightly/v3/plugins/redhat/java/latest/ in Firefox, I get the error: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
> 
> About the raw data, yes the surge.sh script is using index.html and it works, but the rendering is not nice in chrome. so i tried json. I'll see if i can try another file extension: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L44-L52 like index.cgi

Sounds good, for me it's an optional feature to be able to view the `meta.yaml` in the browser so don't break your back over it. :smile:

**Comment by sunix** [comment]
for the index output, index.cgi did not work ... so keeping index.json. and in firefox you can show the content clicking in the raw tab:
Selection_378

**Review by ericwill — APPROVED** [review]

**Pull request merged**
