### PR TITLE
chore: plugin reg updates to move away from download.jboss.org (CRW-2662) & update to newer versions

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

Fix / chore: followup to #19952 

Removals:

* remove obsolete node-debug and node-debug2
* wsdl2rest removed (per @apupier this is no longer needed)

Updates / URL changes:

* vscode-js-debug 1.52.2 -> 1.66.0 (also fix GH project URL)
* clangd 0.1.5 -> 0.1.15 
* cdt-gdb-vscode 0.0.91 -> 0.0.92
* php intelephense-client 1.5.4 -> 1.8.2
* camelk 0.0.26 -> 0.0.30
* microprofile-0.1.1 -> 0.3.0
* quarkus 1.7 -> 1.9
* fabric8-analytics 0.2.1 (was mislabelled as 0.1.0) -> 0.3.5
* project-initializer 0.0.10 -> 0.2.1
* openshift-connector 0.2.9 -> 0.2.13
* php-debug 1.13 -> 1.22.0
* eslint-2.1.1 -> 2.1.20

URL change only:

* cdt-vscode-0.0.7-75cf95 (unchanged, just moved host)
* python (unchanged, just moved host)
* quarkus 1.5 -> 1.5 (unchanged, just moved host; needed for JDK 8)
* java-debug-0.26.0 (moved host only)
* redhat.java-0.82.0 (moved host only)
* redhat.java-0.63.0 (moved host only; for JDK 8)
* mta 0.0.63 (moved host only) @johnsteele FYI if you want something newer, submit a PR
* kubernetes-tools-1.2.1 (moved host only)
* sonarlint-1.20.1 (moved host only)

Questions:

* apache-camel 0.1.5 -> 0.2.0 **** NOT SURE about `trustedHashes` annotation? @apupier 
* xml 0.1.7 **** NOT SURE about `skipDependencies` annotation?  @benoitf 

This PR also includes the changes in https://github.com/eclipse-che/che-plugin-registry/pull/1221 

Change-Id: I5dec0733ab2fc316027cfae42ecd513b17546493
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19952
https://issues.redhat.com/browse/CRW-2662

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
Have you tested those versions ?

**Comment by nickboldt** [comment]
> Have you tested those versions ?

hahaha, no. that's what the Happy Path is for, right? :D

**Comment by benoitf** [comment]
@nickboldt happy path tests are not checking all the extensions (and it's not working for now)

I would just change the download link without changing/upgrading to newer versions

**Review by benoitf — CHANGES_REQUESTED** [review]
please don't change version range. It might not work at all when upgrading to newer versions

**Comment by nickboldt** [comment]
> please don't change version range

Not always possible, unless we simply copy files from dl.jb.o -> gh release. I figured this was a good opportunity to update to newer or latest deps.

**Comment by nickboldt** [comment]
fair enough... I'll adapt my 'push to GH' script [1] so we can park a dozen files into the same gh release instead of producing a dozen individual releases w/ one asset per release [2]. 

[1] https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/blob/main/build/copyFileToGHRelease.sh

[2] https://github.com/redhat-developer/codeready-workspaces-vscode-extensions/releases/tag/0.0.7-75cf95-cdt-vscode-assets

**Comment by angelozerr** [comment]
>no idea what is the trustedHashes but the only place where I see it in the PR is for VS Code XML, not Camel.
>https://github.com/eclipse-che/che-plugin-registry/pull/1222/files#diff->325b78f5d70f8f6957b5b639b2ded282cf0ed56590cb6458a4020462b63c1d8aR469

>so redirecting to @angelozerr

@fbricon @rgrunber have you some ideas?

**Comment by fbricon** [comment]
trusted hashes concern the lemminx binaries downloaded by vscode-xml. Once downloaded, we check their hash is valid

**Comment by nickboldt** [comment]
replaced by https://github.com/eclipse-che/che-plugin-registry/pull/1224 -- simpler solution (just move files)

**Comment by nickboldt** [comment]
@fbricon @angelozerr @apupier 

If you publish new .vsix files for use with Che or CRW, you'll need to put them somewhere other than download.jboss.org in future. If you're already pushing to open-vsx, cool, I can use those in future. 

If you're not, then we'll need to find a new publishing mechanism (eg., to GH release). Hit me up (slack, GH/JIRA issue) if this applies to you.

**Comment by apupier** [comment]
All extensions with redhat as a publisher are pushed to Open VSX already, that's a requirement from Marketing.

**Pull request closed without merging**
