### PR TITLE
fix: add missed resource limits/requests for che-theia/lates

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>

### What does this PR do?
Adds missed cpuLimit and cpuRequest into che-theia/latest ediitor.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20270

### How to test this PR?

Check if `theia-ide` component in`eclipse/che-theia/latest` plugin contains  
```yaml
          memoryLimit: 512M
          cpuLimit: 1500m
          cpuRequest: 100m
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
Thanks for quick fix

**Review by benoitf — APPROVED** [review]
👍

**Comment by benoitf** [comment]
probably need to backport it to 7.34.x branch and check for downstream as well

**Comment by svor** [comment]
> probably need to backport it to 7.34.x branch and check for downstream as well
@benoitf 
-  In downstream we have only latest and all values are here
-  I backport it to 7.34.x when current one will be merged

**Pull request merged**
