### PR TITLE
chore(icon): Rename icon name

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
rename eclipse-che-icon to default

also take [downstream changes](https://github.com/redhat-developer/codeready-workspaces/pull/518) to upstream 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19771

### How to test this PR?
Browse plugins from che-theia and check if icons are displayed

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: Ifa745375b20b56c38b87c723862d67b61757976b
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by ericwill — APPROVED** [review]

**Comment by benoitf** [comment]
@Ohrimenko1988 could you tell me if openshift test failure is related to this PR or not ?

**Comment by ericwill** [comment]
> @Ohrimenko1988 could you tell me if openshift test failure is related to this PR or not ?

Looks like a timeout issue to me but will wait for @Ohrimenko1988 to comment

**Comment by benoitf** [comment]
I can try to relaunch the tests in the meantime

**Pull request merged**
