### PR TITLE
feat: Embed OpenVsx in plug-in registry with few vsix files

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Include OpenVSX in the plug-in registry

It will include some vsix coming from the `openvsx-sync.json` file (like 5 extensions for now)

- remove alpine based image and use only ubi8 base image

### Screenshot/screencast of this PR
image

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/20549

### How to test this PR?
Build the image (or use my image) and then starts Che using that image:

example: `chectl server:deploy --platform=... --che-operator-cr-patch-yaml=...patch-pluginregistry.yaml` with cr patch being

```yaml
spec:
  components:
    pluginRegistry:
      deployment:
        containers:
          - image: 'quay.io/fbenoit/che-plugin-registry:openvsx-20220729'
            resources:
              limits:
                memory: '1536Mi'
```

you should be able to use it by using CheTheia (which consume the plugin-registry API)

Then, for example by using VS Codium or another instance, edit the product.json of the app to point to the instance of this openvsx instance

For example on macOS, edit `./Contents/Resources/app/product.json` from `/Applications/VSCodium.app` folder
by updating content to
```json
  "extensionsGallery": {
    "serviceUrl": "https://192.168.205.14.nip.io/plugin-registry/openvsx/vscode/gallery",
    "itemUrl": "https://192.168.205.14.nip.io/plugin-registry/openvsx/vscode/item"
  },
```
(using your correct nip.io/location)

Then, reset file permissions `xattr -r -d com.apple.quarantine /Applications/VSCodium.app` 

Make sure the Che CaCert certificate is trusted on your mac, (import the file generated by `chectl cacert:export` command)

and then if you go in `extensions` page on VSCodium you should see the few list
image

installation should also work (for example `redhat.vscode-yaml` extension)
image

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: I6b42aa61a6d6b8077441fab270d6950954e29698
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by svor — APPROVED** [review]
Che-Theia works as before, it's possible to install/uninstall plugins from the registry:

screenshot-192 168 49 2 nip io-2022 07 28-12_07_26

**Comment by svor** [comment]
@benoitf it seems openshift-ci built is failed because it uses **rhel.entrypoint.sh** that was removed

**Comment by benoitf** [comment]
@svor ok 👍

**Comment by benoitf** [comment]
@svor it looks like tests have their own Dockerfiles so it looks odd to test stuff using their own copy/fork of the project's Dockerfiles

**Comment by svor** [comment]
@benoitf I agree openshift.ci tests look odd, they should be reworked for sure. But maybe in another PR, without this check we can't merge current PR.

**Comment by benoitf** [comment]
need to make this PR non-draft else openshift-ci tests are not launched

**Comment by benoitf** [comment]
this PR is ready

note: why it's not using directly the OpenVSX image directly
it's due to https://github.com/eclipse/openvsx/issues/498 fixed by https://github.com/eclipse/openvsx/pull/499 but not yet merged

I increased the memory to 512MB in the che-operator but it may not be enough randomly I got some OOM (so in the CR patch for testing this PR I'm using 1536MB)

**Review by svor — APPROVED** [review]
Works as described in the description

Theia with plugins API:
screenshot-eclipse-che apps cluster-sv62d sv62d sandbox1520 opentlc com-2022 07 29-17_04_23

Local VSCodium:
screenshot-nimbusweb me-2022 07 29-16_08_42

**Comment by l0rd** [comment]
@benoitf I was not able to test it. 

I see that open-vsx starts successfully in the plugin registry container but then neither Theia/VSCode are consuming it.

Is there a particular Che Theia image that I should use? And if I want to try it with Che code should this work?
- patch the CheCluster has you mentioned above
- start a workspace sample with VS Code (i.e. golang sample)
- patch the `che-code` DevWorkspaceTemplate to use the image `quay.io/che-incubator-pull-requests/che-code:pr-85-amd64`
- restart the devworkspace

**Comment by benoitf** [comment]
@l0rd 

CheTheia is not consuming at all OpenVSX (it's still consuming the plugin registry as before)
but you can still check that it's working fine there

So basically, there is no change if you're still using CheTheia

but you can look at the 'how to test' section of this PR and try the registry with some Desktop tool (like VSCodium, etc)

and for VSCode, yes if you edit the DevWorkspaceTemplate to use a new image, when workspace will start it'll use the new registry.
It's quite easy to check by looking at the extensions panel as it should display the url of the plug-in registry and you'll have very few extensions if you search for some

**Comment by benoitf** [comment]
you can also look at https://<your-che-cluster>/plugin-registry/openvsx/api/redhat URL

**Comment by l0rd** [comment]
I tried to test yesterday but I had issues with the plugin registry first:

<details>
<summary>After patching the CheCluster (I did that after the installation) the new plugin registry Pod failed to start</summary>
```
$ kubectl describe pod plugin-registry-85d75dbf64-w6vq9
Name:         plugin-registry-85d75dbf64-w6vq9
Namespace:    eclipse-che
Priority:     0
Node:         ip-10-0-138-61.ec2.internal/10.0.138.61
Start Time:   Thu, 04 Aug 2022 18:09:46 +0300
Labels:       app=che
              app.kubernetes.io/component=plugin-registry
              app.kubernetes.io/instance=che
              app.kubernetes.io/managed-by=che-operator
              app.kubernetes.io/name=che
              app.kubernetes.io/part-of=che.eclipse.org
              component=plugin-registry
              pod-template-hash=85d75dbf64
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.128.2.56"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.128.2.56"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: restricted
Status:       Running
IP:           10.128.2.56
IPs:
  IP:           10.128.2.56
Controlled By:  ReplicaSet/plugin-registry-85d75dbf64
Containers:
  plugin-registry:
    Container ID:   cri-o://a7dba0608d551f094e454fc7e769ba33b88a9f709412ec795516f6de33fb1c7e
    Image:          quay.io/fbenoit/che-plugin-registry:openvsx-20220729
    Image ID:       quay.io/fbenoit/che-plugin-registry@sha256:532071687d9d920e7326aa1a6d42cee249cf601707ef0dc4a260e539d8100720
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    124
      Started:      Thu, 04 Aug 2022 18:10:19 +0300
      Finished:     Thu, 04 Aug 2022 18:10:25 +0300
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     700m
      memory:  1536Mi
    Requests:
      cpu:      100m
      memory:   32Mi
    Liveness:   http-get http://:8080/plugins/ delay=30s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:8080/plugins/ delay=3s timeout=3s period=10s #success=1 #failure=10
    Environment Variables from:
      plugin-registry  ConfigMap  Optional: true
    Environment:
      CM_REVISION:  45920
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8pmbl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-8pmbl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  creationTimestamp: "2022-08-04T08:19:31Z"
  finalizers:
  - checluster.che.eclipse.org
  - cheGateway.clusterpermissions.finalizers.che.eclipse.org
  - cheWorkspaces.clusterpermissions.finalizers.che.eclipse.org
  - namespaces-editor.permissions.finalizers.che.eclipse.org
  - devWorkspace.permissions.finalizers.che.eclipse.org
  - oauthclients.finalizers.che.eclipse.org
  - dashboard.clusterpermissions.finalizers.che.eclipse.org
  - consolelink.finalizers.che.eclipse.org
  generation: 4
  name: eclipse-che
  namespace: eclipse-che
  resourceVersion: "184882"
  uid: 981d7d67-8552-4e38-95f7-30914f9bcb3b
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard: {}
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: "5432"
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       54s                default-scheduler  Successfully assigned eclipse-che/plugin-registry-85d75dbf64-w6vq9 to ip-10-0-138-61.ec2.internal
  Normal   AddedInterface  53s                multus             Add eth0 [10.128.2.56/23] from openshift-sdn
  Normal   Pulled          53s                kubelet            Successfully pulled image "quay.io/fbenoit/che-plugin-registry:openvsx-20220729" in 130.576845ms
  Normal   Pulled          46s                kubelet            Successfully pulled image "quay.io/fbenoit/che-plugin-registry:openvsx-20220729" in 194.583121ms
  Normal   Pulling         22s (x3 over 53s)  kubelet            Pulling image "quay.io/fbenoit/che-plugin-registry:openvsx-20220729"
  Normal   Created         22s (x3 over 53s)  kubelet            Created container plugin-registry
  Normal   Started         22s (x3 over 53s)  kubelet            Started container plugin-registry
  Normal   Pulled          22s                kubelet            Successfully pulled image "quay.io/fbenoit/che-plugin-registry:openvsx-20220729" in 148.184037ms
  Warning  BackOff         1s (x5 over 41s)   kubelet            Back-off restarting failed container
```
</details>

I changed the memory limit to 1800Mi and the plugin registry started successfully. But then the dashboard started to be unresponsive:

<details>
<summary>In the logs I got "Unexpected error null"</summary>
Starting Dashboard backend server...
Static server's serving "/public" on 0.0.0.0:8080/
Che Dashboard swagger is running on "dashboard/api/swagger".
├── * (OPTIONS)
└── / (-)
    ├── * (HEAD, GET)
    ├── dashboard (-)
    │   ├── /api (-)
    │   │   ├── /cluster-config (GET)
    │   │   ├── /cluster-info (GET)
    │   │   ├── /namespace/:namespace (-)
    │   │   │   ├── /devworkspaceId/:devworkspaceId/kubeconfig (POST)
    │   │   │   ├── /devworkspaces (GET, POST)
    │   │   │   │   └── /:workspaceName (GET, PATCH, DELETE)
    │   │   │   ├── /devworkspacetemplates (GET, POST)
    │   │   │   │   └── /:templateName (PATCH)
    │   │   │   └── /dockerconfig (GET, PUT)
    │   │   ├── /server-config (GET)
    │   │   ├── /swagger (GET)
    │   │   │   ├── / (GET)
    │   │   │   ├── /* (GET)
    │   │   │   ├── /initOAuth (GET)
    │   │   │   ├── /json (GET)
    │   │   │   ├── /static/* (HEAD, GET)
    │   │   │   ├── /uiConfig (GET)
    │   │   │   └── /yaml (GET)
    │   │   └── /websocket (GET)
    │   └── /f (GET)
    └── f (GET)

(node:6) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server listening at http://0.0.0.0:8080
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
Unexpected error null
</details>

I have tried to reinstall Che but the dashboard was still not working. I am retrying today.

**Comment by l0rd** [comment]
And as discussed we should introduce a check of the variable `START_OPENVSX`: if it's not set or if it's set to `false` we should not start the embedded open-vsx.

I have created a separate issue for the opererator to set this variable to `true` if the `pluginRegistry.openVSXURL` hasn't been specified in the CheCluster: https://github.com/eclipse/che/issues/21611.

**Comment by benoitf** [comment]
Added a fixup for `START_OPENVSX`

**Comment by l0rd** [comment]
I was able to move a little bit forward. 

Although I couldn't test with `che-code` (but that's probably related to [this PR](https://github.com/che-incubator/che-code/pull/85/files#r938952764), thanks @benoitf for fixing it right away) I could list the extensions at `/openvsx/api/redhat`:

image

Anyway I still faced the memory problem:

plugin-registry-fail-to-start

Based on that I would recommend a more robust memory setup done by che-operator:
- if `pluginRegistry.openVSXURL` is NOT set we should set plugin registry memory:
  - limit to 2Gi
  - request to 500Mi
- otherwise set the old (and less demanding) memory settings

Note to self: to test with che-code of PR use

```
https://<my-che-url>/#https://github.com/che-samples/python-hello-world/tree/devfilev2&storageType=ephemeral&che-editor=https://gist.githubusercontent.com/l0rd/0cf6f155f49d0ab92b70986ceabacc58/raw/40be93578f4478b9bdd5a5a27e35da24ab7f9b8a/devfile.yaml
```

**Comment by benoitf** [comment]
merging as now che-operator should default to open-vsx.org and then it means the local OpenVSX instance is not started

**Pull request merged**
