### PR TITLE
chore: use name instead of displayName in generated editor devfile

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: Valerii Svydenko <vsvydenk@redhat.com>

### What does this PR do?
Use `metadata.name` instead of `metadata.displayName` to generate devfile.yaml.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/21704

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by nickboldt — COMMENTED** [review]
I like the idea but can we use a string like "ws-skeleton/jupyter/5.7.0" when creating a subdomain? 

Maybe it's better to filter `name` into just the last two sections, removing slashes, dashes and dots, so the prefix is relatively short (and we don't hit the 63 char limit (and character restrictions due to RFC-1123) imposed by OpenShift) ? 

Thus from `name: ws-skeleton/jupyter/5.7.0` we would get `jupyter570`
and from `name: eclipse/che-theia/next` we would get `chetheianext`

?

Or even shorter names could be done if the 3rd segment is not "insiders" or "next", and end up with:

* `name: eclipse/che-theia/7.55.0` we would get `chetheia`
* `name: eclipse/che-theia/next` we would get `chetheianext`
* `name: ws-skeleton/jupyter/5.7.0` we would get `jupyter`

**Comment by svor** [comment]
replaced by https://github.com/eclipse-che/che-plugin-registry/pull/1444

**Pull request closed without merging**
