### PR TITLE
Add the "OWNERS" file to the "che-plugin-registry" repository.

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>

### What does this PR do?
Add the "OWNERS" file to the "che-plugin-registry" repository.

### What issues does this PR fix or reference?

Issue: https://github.com/eclipse/che/issues/19556

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ericwill — COMMENTED** [review]
I would add @nickboldt as well

**Review by ericwill — APPROVED** [review]

**Comment by benoitf** [comment]
https://github.com/eclipse-che/che-plugin-registry/blob/master/.github/CODEOWNERS should be in sync so probably need to have a github action to ensure that if we modify one file the other is updated

**Comment by Ohrimenko1988** [comment]
> https://github.com/eclipse-che/che-plugin-registry/blob/master/.github/CODEOWNERS should be in sync so probably need to have a github action to ensure that if we modify one file the other is updated

Good catch, thank you. Let me play with this functionality (owners list for openshift ci job) to clarify how exactly it will look like, and after that we can decide how to improve that.

**Comment by Ohrimenko1988** [comment]
Implemented on the openshift ci side

**Pull request closed without merging**
