### PR TITLE
Update Zowe Explorer latest release

### PR DESCRIPTION
**Pull request by jellypuno**
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

### What does this PR do?

Updates Zowe Explorer to its latest version v1.16.0

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by jellypuno** [comment]
I've updated the link but I cannot re-run the pipeline. Kindly re-run please. It should be okay now. Thank you!

**Review by ericwill — APPROVED** [review]

**Comment by MichalMaler** [comment]
https://issues.redhat.com/browse/CRW-1966

**Comment by MichalMaler** [comment]
Then it shouldn't be labeled as a new CRW feature, which is requested to document for RNaKI.

**Comment by themr0c** [comment]
@ericwill thank you for the precision.

The new&noteworthy label is marking new features  for upstream. If we need some further triage, let's do it in Jira.

**Comment by MichalMaler** [comment]
Oh, Eric, thank you for that, I forgot to set the status for "Not required (won't be featured in RNaKI doc)". Now it is all clear :) The best practice is sharp action. Now I know that we have to create JIRA issues for all of these, even for those, which not lad in RNaKI, and treat their RNaKI status adequately.

**Pull request merged**
