### PR TITLE
chore: Upgrade VS Code Metals, the Scala language client, to version 1.10.15

### PR DESCRIPTION
**Pull request by sideeffffect**
Signed-off-by: sideeffffect ondra.pelech@gmail.com

/cc @svor 

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sideeffffect** [comment]
Btw I'm getting this error with newer Metals:
```
ERROR:Activating extension 'Scala (Metals)' failed:Error: The language client requires VS Code version ^1.52.0 but received version 1.50.0
```
Are there any plans to upgrade Theia to a newer version that is analogous to VS Code >= 1.52 ?

**Comment by svor** [comment]
> Btw I'm getting this error with newer Metals:
> 
> ```
> LOG:PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/scalameta.metals.latest.sgbepgrhbt.scalameta.metals-1.10.11.vsix/extension/out/extension)
> ...
> ERROR:Activating extension 'Scala (Metals)' failed:Error: The language client requires VS Code version ^1.52.0 but received version 1.50.0
> ```
> 
> Are there any plans to upgrade Theia to a newer version that is analogous to VS Code >= 1.52 ?
> 
> But it is a bit strange that Metals 1.10.11 would require >= 1.52. According to its source code, >= 1.43 should be OK: https://github.com/scalameta/metals-vscode/blob/v1.10.11/package.json#L629 /cc @tgodzik

@sideeffffect could you try to run your updated plugin with `next` version of `che-theia` editor. You can do that by adding next component into your devfile:
```
components:
  - id: eclipse/che-theia/next
    type: cheEditor
```
VS Code API was already updated to 1.53.2 https://github.com/eclipse-theia/theia/pull/9959

**Comment by sideeffffect** [comment]
> ```
> components:
>  - id: eclipse/che-theia/next
>    type: cheEditor
>```
For 
```
apiVersion: 1.0.0
metadata:
  name: scala-sbt-1eoro
projects:
  - name: console-scala-simple
    source:
      location: 'https://github.com/che-samples/scala-sbt'
      type: git
      branch: master
components:
  - id: eclipse/che-theia/next
    type: cheEditor
  - id: scalameta/metals/latest
    type: chePlugin
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/7.39.2/v3/'
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 1500Mi
    type: dockerimage
    volumes:
      - name: sbt
        containerPath: /home/user/.sbt
      - name: ivy2
        containerPath: /home/user/.ivy2
      - name: coursier
        containerPath: /home/user/.cache/coursier
      - name: metals
        containerPath: /home/user/.cache/metals
      - name: bloop
        containerPath: /home/user/.cache/bloop
    alias: sbt
    image: 'quay.io/devfile/universal-developer-image:ubi8-1e8c2c9'
    env:
      - value: '-XX:MaxRAMPercentage=80 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JDK_JAVA_OPTIONS
  - id: redhat/vscode-yaml/latest
    type: chePlugin
commands:
  - name: sbt REPL
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-scala-simple'
        type: exec
        command: ./sbt
        component: sbt
  - name: sbt compile
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-scala-simple'
        type: exec
        command: ./sbt compile
        component: sbt
  - name: sbt test
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-scala-simple'
        type: exec
        command: ./sbt test
        component: sbt
  - name: sbt run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-scala-simple'
        type: exec
        command: ./sbt run
        component: sbt

```
I'm getting
```
Add eth0 [10.130.5.122/23] from openshift-sdn

Pulling image "registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8@sha256:e709e89bd1ab1612baad039ad6b824b027a070ff0a37be3395202faa55518e09"

Successfully pulled image "registry.redhat.io/codeready-workspaces/pluginbroker-metadata-rhel8@sha256:e709e89bd1ab1612baad039ad6b824b027a070ff0a37be3395202faa55518e09" in 913.075988ms

Created container pluginbroker-metadata-rhel8-e709e89bd1

Starting plugin metadata broker

Started container pluginbroker-metadata-rhel8-e709e89bd1

Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'http://plugin-registry.codeready-workspaces-operator.svc:8080/v3/plugins/eclipse/che-theia/next/meta.yaml': Downloading http://plugin-registry.codeready-workspaces-operator.svc:8080/v3/plugins/eclipse/che-theia/next/meta.yaml failed. Status code 404. Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

<html><head>

<title>404 Not Found</title>

</head><body>

<h1>Not Found</h1>

<p>The requested URL was not found on this server.</p>

</body></html>

Failed to run the workspace: "Plugins installation process failed. Error: Plugin brokering process for workspace workspace9uqbxm2nwodb3vl3 failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'http://plugin-registry.codeready-workspaces-operator.svc:8080/v3/plugins/eclipse/che-theia/next/meta.yaml': Downloading http://plugin-registry.codeready-workspaces-operator.svc:8080/v3/plugins/eclipse/che-theia/next/meta.yaml failed. Status code 404. Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL was not found on this server.</p> </body></html> "
```

**Comment by sideeffffect** [comment]
Yep, that works! Thanks. Now I just need the newest Metals (this PR) to work with the latest version of Scala ( https://github.com/che-samples/scala-sbt ).

**Review by svor — APPROVED** [review]

**Pull request merged**
