### PR TITLE
chore: clean up description/attribute.title and displayName values for consistency and compliance with branding/trademark (#21704) (CRW-3098)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: clean up description/attribute.title and displayName values for consistency and compliance with branding/trademark (#[21704](https://github.com/eclipse/che/issues/21704)) ([CRW-3098](https://issues.redhat.com//browse/CRW-3098));

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
* https://github.com/eclipse/che/issues/21704
* https://issues.redhat.com/browse/CRW-3098

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
See downstream PR: https://github.com/eclipse-che/che-plugin-registry/pull/1441

**Review by amisevsk — COMMENTED** [review]
This works as a solution but it's a little strange to me to add a new field to metadata that's not listed in the devfile spec: https://devfile.io/docs/2.2.0-alpha/devfile-schema#metadata. I think using `name: publisher/name/version` is a holdover from the plugin registries of yore -- Devfile has metadata fields for provider/version now.

We could merge this PR as-is, but it would need to be coordinated with dashboard changes (i.e. dashboard PR to use `workspacePrefix` in place of `displayName` would need to come first). Merging now would result in Che `next` workspaces failing to start (as dashboard would attempt to use displayNames that are invalid as k8s names).

Edit to add: this is a different way of handling `name`/`displayName` than for workspace devfile samples: for devfiles, we use the `name` as the k8s object name, and displayName to show additional info -- see e.g. the devfile for [Java Springboot](https://github.com/che-samples/java-guestbook/blob/devfilev2/devfile.yaml)

**Comment by svor** [comment]
@nickboldt I'd avoid adding new fields like `workspacePrefix`. 
Here is a PR https://github.com/eclipse-che/che-plugin-registry/pull/1442 that stops using `displayName` at the workspace creation.
So, let's change only `displayName` and `description`

**Comment by nickboldt** [comment]
I like the idea but can we use a string like "ws-skeleton/jupyter/5.7.0" when creating a subdomain? 

Maybe it's better to filter `name` into just the last two sections, removing slashes, dashes and dots, so the prefix is relatively short (and we don't hit the 63 char limit imposed by OpenShift) ? 

Thus from `name: ws-skeleton/jupyter/5.7.0` we would get `jupyter570`
and from `name: eclipse/che-theia/next` we would get `chetheianext`

?

**Review by svor — APPROVED** [review]

**Review by amisevsk — APPROVED** [review]

**Pull request merged**
