### PR TITLE
Update Che-Theia repository location

### PR DESCRIPTION
**Pull request by azatsarynnyy**
### What does this PR do?
Updates Che-Theia repository location.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19391

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
I think it'll break https://github.com/eclipse/che-plugin-registry/blob/master/tools/build/tests/editor/che-editor-analyzer.spec.ts

(it seems tests are not ran when we modify the yaml)

**Review by benoitf — CHANGES_REQUESTED** [review]
I think tests need to be adapted

**Review by ericwill — COMMENTED** [review]
Should the `id` fields change from `eclipse/che-theia/*` to `eclipse-che/che-theia/*`?

**Comment by benoitf** [comment]
I think it may break more stuff ? Like for now images are still on quay.io/eclipse/

**Comment by azatsarynnyy** [comment]
@benoitf I've just updated the tests

**Comment by azatsarynnyy** [comment]
> Should the `id` fields change from `eclipse/che-theia/*` to `eclipse-che/che-theia/*`?

no, it's just a new GH repository link

**Review by benoitf — APPROVED** [review]

**Review by ericwill — APPROVED** [review]

**Pull request merged**
