### PR TITLE
Yarn v2 migration

### PR DESCRIPTION
**Pull request by ericwill**
Signed-off-by: Eric Williams <ericwill@redhat.com>

### What does this PR do?
Migrates the che-plugin-registry to use yarn v2

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes eclipse/che#19581

### How to test this PR?

Checkout the branch and run `build.sh`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
This is a draft because it doesn't work yet. Some remarks:
* not sure if `nodeLinker: node-modules` is correct, or if we should be using pnp
* `build.sh` is failing on the `yarn --cwd "$(pwd)/tools/build" build` step -- it appears to be some bug with using `--cwd`?
* if I pass the path and do not use the `--cwd` option, the build still fails with `CONCURRENTLY_OPTS` unbound

**Review by benoitf — APPROVED** [review]
let's try

**Comment by ericwill** [comment]
Looks like report publishing failed: https://github.com/eclipse-che/che-plugin-registry/actions/runs/789941031

But to me it looks more like a git error, not a yarn v2 related issue.

**Comment by benoitf** [comment]
yes I restarted and it succeeded

**Pull request merged**
