### PR TITLE
chore: add memoryRequest for plugins sidecars

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Adds memory request in 20 megabytes for the plugin sidecars.

PR with pull-request check for memory and cpu limitations https://github.com/eclipse-che/che-plugin-registry/pull/1022

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/16685

### How to test this PR?

 
A plugin registry with memory requests is temporary published to https://vgulyy-plugin-registry.surge.sh/v3/
 
1. create any workspace, install recommended plugins
2. stop the workspace, go to devfile on the dashboard
3. add registry URL to all the plugins to load them from temporary plugin registry
```
registryUrl: 'https://vgulyy-plugin-registry.surge.sh/v3'
```
4. start workspace, check how plugin works

### Tested on:
- local minikube
- workspaces.openshift.com
- openshift 4.7 cluster on RHPDS

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by svor** [comment]
@vitaliy-guliy one question, I see [`che-machine-exec` and `remote-runtime-injector`](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L123) have memoryRequest: 32Mi, shouldn't we use the same value for sidecars or you think 20Mi is enough?

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy one question, I see [`che-machine-exec` and `remote-runtime-injector`](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L123) have memoryRequest: 32Mi, shouldn't we use the same value for sidecars or you think 20Mi is enough?

I have tested it with 20Mb and can say, that it works nicely.
`memoryRequest` is used when initializing the container (as I understand). A process, that running inside the container, can always ask for the required amount of memory when it's needed.

**Review by svor — APPROVED** [review]

**Pull request merged**
