### PR TITLE
chore: Add separate endpoint for webviews

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Adds a new endpoint to have a different domain to load the webview static resources instead of getting them (if configured) from CDN.

### What issues does this PR fix or reference?

Part of https://issues.redhat.com/browse/CRW-3885

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by svor** [comment]
@vitaliy-guliy could you please rebase the pr to pickup latest changes from **main** that fix PR checks

**Review by azatsarynnyy — COMMENTED** [review]
Should the `urlRewriteSupported` has the same value for both Che-Code versions?

**Comment by svor** [comment]
As far as I know all redirect endpoints should have **urlRewriteSupported** set to **false** except the main IDE endpoint. 
See related issue https://issues.redhat.com/browse/CRW-3600

**Comment by vitaliy-guliy** [comment]
Let's postpone with this pull request, as it was decided to load the webview static resources from the same host as vscode main frame.

**Pull request closed without merging**
