### PR TITLE
Upgrade VS Code Language support for Camel to 0.0.33 eclipse/che#19818

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by apupier** [comment]
I do not find the reason of happy path jobto fail.

The error I found is not giving much information:
https://github.com/eclipse-che/che-plugin-registry/pull/959/checks?check_run_id=2610393363#step:12:7065
{noformat}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e2e@1.0.0 test-happy-path: `./generateIndex.sh && npm run lint && npm run tsc && mocha --opts mocha-happy-path.opts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e2e@1.0.0 test-happy-path script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/seluser/.npm/_logs/2021-05-18T12_58_06_273Z-debug.log
{noformat}

**Comment by benoitf** [comment]
I increased timeout delay yesterday as it was taking too long time. I restarted jobs

**Comment by apupier** [comment]
> I increased timeout delay yesterday as it was taking too long time. I restarted jobs

failed again. I checked that on latest master (so that the tiemout wasn't configured there)

**Review by benoitf — APPROVED** [review]

**Review by ericwill — APPROVED** [review]

**Pull request merged**
